default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: real_estate_ad_management_development

test:
  <<: *default
  database: real_estate_ad_management_test
  host: <%= ENV["TEST_DATABASE_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  

production:
  <<: *default
  database: real_estate_ad_management_production
  username: real_estate_ad_management
  password: <%= ENV["REAL_ESTATE_AD_MANAGEMENT_DATABASE_PASSWORD"] %>
