default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: real_estate_ad_management_development

test:
  <<: *default
  database: real_estate_ad_management_test
  host: <%= ENV["TEST_DATABASE_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  

production:
  <<: *default
  host: <%= ENV["PRODUCTION_DATABASE_HOST"] %>
  username: <%= ENV["PRODUCTION_DATABASE_USER_NAME"] %>
  password: <%= ENV["PRODUCTION_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
